version: '3.8'

services:
  # FreeSWITCH - PBX/VoIP Engine
  freeswitch:
    image: safarov/freeswitch:latest
    container_name: freeswitch_pbx
    restart: unless-stopped
    ports:
      - "5060:5060/udp" # SIP
      - "5061:5061/tcp" # SIP TLS
      - "7443:7443/tcp"  # WSS for WebRTC
      - "8021:8021/tcp"  # ESL (Event Socket Layer)
      - "16384-32768:16384-32768/udp" # RTP
    volumes:
      - ./freeswitch/conf:/usr/local/freeswitch/conf
      - freeswitch_db:/usr/local/freeswitch/db
      - freeswitch_recordings:/usr/local/freeswitch/recordings
    environment:
      - FS_USER=freeswitch
      - FS_GROUP=freeswitch
    healthcheck:
      test: ["CMD", "fs_cli", "-x", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Backend - Node.js Fastify API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: voicewoot_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      freeswitch:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./dev.db:/app/dev.db
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: "file:/app/dev.db"
      FS_ESL_HOST: "freeswitch"
      FS_ESL_PORT: "8021"
      FS_ESL_PASSWORD: "ClueCon"
      LOG_LEVEL: "debug"
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend - React + Vite
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: voicewoot_frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  freeswitch_db:
    driver: local
  freeswitch_recordings:
    driver: local
